name: barterra2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core:
  animated_theme_switcher:
  shared_preferences:
  google_fonts:
  flutter_bloc:
  image_picker:
  intl: ^0.17.0
  path_provider:
  path:
  package_info_plus:
  easy_localization: ^3.0.1
  flutter_native_splash:
  geolocator:
  animations:
  dio:
  cached_network_image:
  flutter_slidable:
  flutter_svg:
  shimmer: any
  map_launcher:
  file_picker:
  camera:
  image_cropper: ^3.0.1
  scrollable_positioned_list:
  url_launcher:
  flutter_cache_manager:
  need_resume:
  firebase_auth: ^4.2.0
  firebase_auth_web: ^5.2.0
  firebase_auth_platform_interface: ^6.11.6
  cloud_firestore: ^4.3.0
  firebase_storage: ^11.0.10
  firebase_database: ^10.0.9
  country_picker: ^2.0.19
  mask_text_input_formatter: ^2.4.0
  flutter_keyboard_visibility: ^5.4.0
  graphql_flutter: ^5.1.0
  getworld: any
  fluttertoast: ^8.1.2
  wave: ^0.2.2
  flutter_custom_clippers: ^2.1.0
  google_sign_in: ^5.4.4
  get_it: ^7.2.0
  either_dart: ^0.3.0
  equatable: ^2.0.5
  data_connection_checker_nulls: ^0.0.2
  injectable: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/translations/
    - assets/country/
