// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpOIiVq_M-u8prCcjtaH-VizMJEzIPfI',
    appId: '1:402408740898:web:6333f97f0c50f8d336127b',
    messagingSenderId: '402408740898',
    projectId: 'barterra-c61e1',
    authDomain: 'barterra-c61e1.firebaseapp.com',
    databaseURL: 'https://barterra-c61e1-default-rtdb.firebaseio.com',
    storageBucket: 'barterra-c61e1.appspot.com',
    measurementId: 'G-EM999B3RKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCPQg238M5dE0V0Wt4cnlz5CNMSNB_iNY',
    appId: '1:402408740898:android:7ecd1e2e7078884736127b',
    messagingSenderId: '402408740898',
    projectId: 'barterra-c61e1',
    databaseURL: 'https://barterra-c61e1-default-rtdb.firebaseio.com',
    storageBucket: 'barterra-c61e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQt3bzV1rWfUOn2ooi-JacGTMZKblgRN4',
    appId: '1:402408740898:ios:0709d917e532278336127b',
    messagingSenderId: '402408740898',
    projectId: 'barterra-c61e1',
    databaseURL: 'https://barterra-c61e1-default-rtdb.firebaseio.com',
    storageBucket: 'barterra-c61e1.appspot.com',
    iosClientId: '402408740898-rvo96lhdp6hoptiq1p9q438fn2mpcl5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.barterra2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQt3bzV1rWfUOn2ooi-JacGTMZKblgRN4',
    appId: '1:402408740898:ios:0709d917e532278336127b',
    messagingSenderId: '402408740898',
    projectId: 'barterra-c61e1',
    databaseURL: 'https://barterra-c61e1-default-rtdb.firebaseio.com',
    storageBucket: 'barterra-c61e1.appspot.com',
    iosClientId: '402408740898-rvo96lhdp6hoptiq1p9q438fn2mpcl5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.barterra2',
  );
}
